#!/usr/bin/env python

import argparse
import json
import sys

import mdstat


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("path", nargs="?", default="/proc/mdstat")
    args = parser.parse_args()

    json.dump(mdstat.parse(args.path), sys.stdout, indent=4)
